//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.27 at 12:09:46 AM CDT 
//


package org.example.nose;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.nose package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.nose
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DisplayAllReservationResponse }
     * 
     */
    public DisplayAllReservationResponse createDisplayAllReservationResponse() {
        return new DisplayAllReservationResponse();
    }

    /**
     * Create an instance of {@link DisplayAllFlightResponse }
     * 
     */
    public DisplayAllFlightResponse createDisplayAllFlightResponse() {
        return new DisplayAllFlightResponse();
    }

    /**
     * Create an instance of {@link ShowSelectedFlightResponse }
     * 
     */
    public ShowSelectedFlightResponse createShowSelectedFlightResponse() {
        return new ShowSelectedFlightResponse();
    }

    /**
     * Create an instance of {@link DisplayAllReservationResponse.Datos }
     * 
     */
    public DisplayAllReservationResponse.Datos createDisplayAllReservationResponseDatos() {
        return new DisplayAllReservationResponse.Datos();
    }

    /**
     * Create an instance of {@link CreateFlightRequest }
     * 
     */
    public CreateFlightRequest createCreateFlightRequest() {
        return new CreateFlightRequest();
    }

    /**
     * Create an instance of {@link DisplayAllFlightRequest }
     * 
     */
    public DisplayAllFlightRequest createDisplayAllFlightRequest() {
        return new DisplayAllFlightRequest();
    }

    /**
     * Create an instance of {@link CreateFlightResponse }
     * 
     */
    public CreateFlightResponse createCreateFlightResponse() {
        return new CreateFlightResponse();
    }

    /**
     * Create an instance of {@link ReadFlightResponse }
     * 
     */
    public ReadFlightResponse createReadFlightResponse() {
        return new ReadFlightResponse();
    }

    /**
     * Create an instance of {@link ReadReservationRequest }
     * 
     */
    public ReadReservationRequest createReadReservationRequest() {
        return new ReadReservationRequest();
    }

    /**
     * Create an instance of {@link DisplayAllFlightResponse.Datos }
     * 
     */
    public DisplayAllFlightResponse.Datos createDisplayAllFlightResponseDatos() {
        return new DisplayAllFlightResponse.Datos();
    }

    /**
     * Create an instance of {@link CreateFlightReservationResponse }
     * 
     */
    public CreateFlightReservationResponse createCreateFlightReservationResponse() {
        return new CreateFlightReservationResponse();
    }

    /**
     * Create an instance of {@link DisplayAllReservationRequest }
     * 
     */
    public DisplayAllReservationRequest createDisplayAllReservationRequest() {
        return new DisplayAllReservationRequest();
    }

    /**
     * Create an instance of {@link ReadFlightRequest }
     * 
     */
    public ReadFlightRequest createReadFlightRequest() {
        return new ReadFlightRequest();
    }

    /**
     * Create an instance of {@link ReadReservationResponse }
     * 
     */
    public ReadReservationResponse createReadReservationResponse() {
        return new ReadReservationResponse();
    }

    /**
     * Create an instance of {@link ShowSelectedFlightResponse.Datos }
     * 
     */
    public ShowSelectedFlightResponse.Datos createShowSelectedFlightResponseDatos() {
        return new ShowSelectedFlightResponse.Datos();
    }

    /**
     * Create an instance of {@link ShowSelectedFlightRequest }
     * 
     */
    public ShowSelectedFlightRequest createShowSelectedFlightRequest() {
        return new ShowSelectedFlightRequest();
    }

    /**
     * Create an instance of {@link UpdateReservationRequest }
     * 
     */
    public UpdateReservationRequest createUpdateReservationRequest() {
        return new UpdateReservationRequest();
    }

    /**
     * Create an instance of {@link UpdateFlightRequest }
     * 
     */
    public UpdateFlightRequest createUpdateFlightRequest() {
        return new UpdateFlightRequest();
    }

    /**
     * Create an instance of {@link UpdateReservationResponse }
     * 
     */
    public UpdateReservationResponse createUpdateReservationResponse() {
        return new UpdateReservationResponse();
    }

    /**
     * Create an instance of {@link DeleteFlightResponse }
     * 
     */
    public DeleteFlightResponse createDeleteFlightResponse() {
        return new DeleteFlightResponse();
    }

    /**
     * Create an instance of {@link UpdateFlightResponse }
     * 
     */
    public UpdateFlightResponse createUpdateFlightResponse() {
        return new UpdateFlightResponse();
    }

    /**
     * Create an instance of {@link DeleteFlightRequest }
     * 
     */
    public DeleteFlightRequest createDeleteFlightRequest() {
        return new DeleteFlightRequest();
    }

    /**
     * Create an instance of {@link DeleteReservationResponse }
     * 
     */
    public DeleteReservationResponse createDeleteReservationResponse() {
        return new DeleteReservationResponse();
    }

    /**
     * Create an instance of {@link CreateFlightReservationRequest }
     * 
     */
    public CreateFlightReservationRequest createCreateFlightReservationRequest() {
        return new CreateFlightReservationRequest();
    }

    /**
     * Create an instance of {@link DeleteReservationRequest }
     * 
     */
    public DeleteReservationRequest createDeleteReservationRequest() {
        return new DeleteReservationRequest();
    }

}
