//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.16 at 07:58:42 PM CDT 
//


package org.example.nose;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="num_infantes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="num_ninos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="num_adultos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ciudad_origen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ciudad_destino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fecha_salida" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numInfantes",
    "numNinos",
    "numAdultos",
    "ciudadOrigen",
    "ciudadDestino",
    "fechaSalida"
})
@XmlRootElement(name = "ShowSelectedFlightRequest")
public class ShowSelectedFlightRequest {

    @XmlElement(name = "num_infantes")
    protected int numInfantes;
    @XmlElement(name = "num_ninos")
    protected int numNinos;
    @XmlElement(name = "num_adultos")
    protected int numAdultos;
    @XmlElement(name = "ciudad_origen", required = true)
    protected String ciudadOrigen;
    @XmlElement(name = "ciudad_destino", required = true)
    protected String ciudadDestino;
    @XmlElement(name = "fecha_salida", required = true)
    protected String fechaSalida;

    /**
     * Gets the value of the numInfantes property.
     * 
     */
    public int getNumInfantes() {
        return numInfantes;
    }

    /**
     * Sets the value of the numInfantes property.
     * 
     */
    public void setNumInfantes(int value) {
        this.numInfantes = value;
    }

    /**
     * Gets the value of the numNinos property.
     * 
     */
    public int getNumNinos() {
        return numNinos;
    }

    /**
     * Sets the value of the numNinos property.
     * 
     */
    public void setNumNinos(int value) {
        this.numNinos = value;
    }

    /**
     * Gets the value of the numAdultos property.
     * 
     */
    public int getNumAdultos() {
        return numAdultos;
    }

    /**
     * Sets the value of the numAdultos property.
     * 
     */
    public void setNumAdultos(int value) {
        this.numAdultos = value;
    }

    /**
     * Gets the value of the ciudadOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiudadOrigen() {
        return ciudadOrigen;
    }

    /**
     * Sets the value of the ciudadOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiudadOrigen(String value) {
        this.ciudadOrigen = value;
    }

    /**
     * Gets the value of the ciudadDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCiudadDestino() {
        return ciudadDestino;
    }

    /**
     * Sets the value of the ciudadDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCiudadDestino(String value) {
        this.ciudadDestino = value;
    }

    /**
     * Gets the value of the fechaSalida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaSalida() {
        return fechaSalida;
    }

    /**
     * Sets the value of the fechaSalida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaSalida(String value) {
        this.fechaSalida = value;
    }

}
