//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.27 at 12:09:46 AM CDT 
//


package org.example.nose;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datos" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="aerolinea" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="codigo_avion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fecha_salida" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hora_salida" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hora_llegada" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pais_origen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pais_destino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ciudad_origen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ciudad_destino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="precio_tarifa_basica" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="precio_tarifa_clasica" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="precio_tarifa_amplus" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="precio_tarifa_flexible" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="precio_tarifa_premier" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="beneficios_tarifa_basica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="beneficios_tarifa_clasica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="beneficios_tarifa_amplus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="beneficios_tarifa_flexible" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="beneficios_tarifa_premier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="num_asientos_tarifa_basica" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="num_asientos_tarifa_clasica" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="num_asientos_tarifa_amplus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="num_asientos_tarifa_flexible" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="num_asientos_tarifa_premier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datos"
})
@XmlRootElement(name = "ShowSelectedFlightResponse")
public class ShowSelectedFlightResponse {

    @XmlElement(required = true)
    protected List<ShowSelectedFlightResponse.Datos> datos;

    /**
     * Gets the value of the datos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShowSelectedFlightResponse.Datos }
     * 
     * 
     */
    public List<ShowSelectedFlightResponse.Datos> getDatos() {
        if (datos == null) {
            datos = new ArrayList<ShowSelectedFlightResponse.Datos>();
        }
        return this.datos;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="aerolinea" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="codigo_avion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fecha_salida" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="hora_salida" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="hora_llegada" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pais_origen" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pais_destino" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ciudad_origen" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ciudad_destino" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="precio_tarifa_basica" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="precio_tarifa_clasica" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="precio_tarifa_amplus" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="precio_tarifa_flexible" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="precio_tarifa_premier" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="beneficios_tarifa_basica" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="beneficios_tarifa_clasica" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="beneficios_tarifa_amplus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="beneficios_tarifa_flexible" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="beneficios_tarifa_premier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="num_asientos_tarifa_basica" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="num_asientos_tarifa_clasica" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="num_asientos_tarifa_amplus" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="num_asientos_tarifa_flexible" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="num_asientos_tarifa_premier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "aerolinea",
        "codigoAvion",
        "fechaSalida",
        "horaSalida",
        "horaLlegada",
        "paisOrigen",
        "paisDestino",
        "ciudadOrigen",
        "ciudadDestino",
        "precioTarifaBasica",
        "precioTarifaClasica",
        "precioTarifaAmplus",
        "precioTarifaFlexible",
        "precioTarifaPremier",
        "beneficiosTarifaBasica",
        "beneficiosTarifaClasica",
        "beneficiosTarifaAmplus",
        "beneficiosTarifaFlexible",
        "beneficiosTarifaPremier",
        "numAsientosTarifaBasica",
        "numAsientosTarifaClasica",
        "numAsientosTarifaAmplus",
        "numAsientosTarifaFlexible",
        "numAsientosTarifaPremier"
    })
    public static class Datos {

        protected int id;
        @XmlElement(required = true)
        protected String aerolinea;
        @XmlElement(name = "codigo_avion", required = true)
        protected String codigoAvion;
        @XmlElement(name = "fecha_salida", required = true)
        protected String fechaSalida;
        @XmlElement(name = "hora_salida", required = true)
        protected String horaSalida;
        @XmlElement(name = "hora_llegada", required = true)
        protected String horaLlegada;
        @XmlElement(name = "pais_origen", required = true)
        protected String paisOrigen;
        @XmlElement(name = "pais_destino", required = true)
        protected String paisDestino;
        @XmlElement(name = "ciudad_origen", required = true)
        protected String ciudadOrigen;
        @XmlElement(name = "ciudad_destino", required = true)
        protected String ciudadDestino;
        @XmlElement(name = "precio_tarifa_basica")
        protected double precioTarifaBasica;
        @XmlElement(name = "precio_tarifa_clasica")
        protected double precioTarifaClasica;
        @XmlElement(name = "precio_tarifa_amplus")
        protected double precioTarifaAmplus;
        @XmlElement(name = "precio_tarifa_flexible")
        protected double precioTarifaFlexible;
        @XmlElement(name = "precio_tarifa_premier")
        protected double precioTarifaPremier;
        @XmlElement(name = "beneficios_tarifa_basica", required = true)
        protected String beneficiosTarifaBasica;
        @XmlElement(name = "beneficios_tarifa_clasica", required = true)
        protected String beneficiosTarifaClasica;
        @XmlElement(name = "beneficios_tarifa_amplus", required = true)
        protected String beneficiosTarifaAmplus;
        @XmlElement(name = "beneficios_tarifa_flexible", required = true)
        protected String beneficiosTarifaFlexible;
        @XmlElement(name = "beneficios_tarifa_premier", required = true)
        protected String beneficiosTarifaPremier;
        @XmlElement(name = "num_asientos_tarifa_basica")
        protected int numAsientosTarifaBasica;
        @XmlElement(name = "num_asientos_tarifa_clasica")
        protected int numAsientosTarifaClasica;
        @XmlElement(name = "num_asientos_tarifa_amplus")
        protected int numAsientosTarifaAmplus;
        @XmlElement(name = "num_asientos_tarifa_flexible")
        protected int numAsientosTarifaFlexible;
        @XmlElement(name = "num_asientos_tarifa_premier")
        protected int numAsientosTarifaPremier;

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the aerolinea property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAerolinea() {
            return aerolinea;
        }

        /**
         * Sets the value of the aerolinea property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAerolinea(String value) {
            this.aerolinea = value;
        }

        /**
         * Gets the value of the codigoAvion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigoAvion() {
            return codigoAvion;
        }

        /**
         * Sets the value of the codigoAvion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodigoAvion(String value) {
            this.codigoAvion = value;
        }

        /**
         * Gets the value of the fechaSalida property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFechaSalida() {
            return fechaSalida;
        }

        /**
         * Sets the value of the fechaSalida property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFechaSalida(String value) {
            this.fechaSalida = value;
        }

        /**
         * Gets the value of the horaSalida property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHoraSalida() {
            return horaSalida;
        }

        /**
         * Sets the value of the horaSalida property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHoraSalida(String value) {
            this.horaSalida = value;
        }

        /**
         * Gets the value of the horaLlegada property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHoraLlegada() {
            return horaLlegada;
        }

        /**
         * Sets the value of the horaLlegada property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHoraLlegada(String value) {
            this.horaLlegada = value;
        }

        /**
         * Gets the value of the paisOrigen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaisOrigen() {
            return paisOrigen;
        }

        /**
         * Sets the value of the paisOrigen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaisOrigen(String value) {
            this.paisOrigen = value;
        }

        /**
         * Gets the value of the paisDestino property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaisDestino() {
            return paisDestino;
        }

        /**
         * Sets the value of the paisDestino property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaisDestino(String value) {
            this.paisDestino = value;
        }

        /**
         * Gets the value of the ciudadOrigen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCiudadOrigen() {
            return ciudadOrigen;
        }

        /**
         * Sets the value of the ciudadOrigen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCiudadOrigen(String value) {
            this.ciudadOrigen = value;
        }

        /**
         * Gets the value of the ciudadDestino property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCiudadDestino() {
            return ciudadDestino;
        }

        /**
         * Sets the value of the ciudadDestino property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCiudadDestino(String value) {
            this.ciudadDestino = value;
        }

        /**
         * Gets the value of the precioTarifaBasica property.
         * 
         */
        public double getPrecioTarifaBasica() {
            return precioTarifaBasica;
        }

        /**
         * Sets the value of the precioTarifaBasica property.
         * 
         */
        public void setPrecioTarifaBasica(double value) {
            this.precioTarifaBasica = value;
        }

        /**
         * Gets the value of the precioTarifaClasica property.
         * 
         */
        public double getPrecioTarifaClasica() {
            return precioTarifaClasica;
        }

        /**
         * Sets the value of the precioTarifaClasica property.
         * 
         */
        public void setPrecioTarifaClasica(double value) {
            this.precioTarifaClasica = value;
        }

        /**
         * Gets the value of the precioTarifaAmplus property.
         * 
         */
        public double getPrecioTarifaAmplus() {
            return precioTarifaAmplus;
        }

        /**
         * Sets the value of the precioTarifaAmplus property.
         * 
         */
        public void setPrecioTarifaAmplus(double value) {
            this.precioTarifaAmplus = value;
        }

        /**
         * Gets the value of the precioTarifaFlexible property.
         * 
         */
        public double getPrecioTarifaFlexible() {
            return precioTarifaFlexible;
        }

        /**
         * Sets the value of the precioTarifaFlexible property.
         * 
         */
        public void setPrecioTarifaFlexible(double value) {
            this.precioTarifaFlexible = value;
        }

        /**
         * Gets the value of the precioTarifaPremier property.
         * 
         */
        public double getPrecioTarifaPremier() {
            return precioTarifaPremier;
        }

        /**
         * Sets the value of the precioTarifaPremier property.
         * 
         */
        public void setPrecioTarifaPremier(double value) {
            this.precioTarifaPremier = value;
        }

        /**
         * Gets the value of the beneficiosTarifaBasica property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeneficiosTarifaBasica() {
            return beneficiosTarifaBasica;
        }

        /**
         * Sets the value of the beneficiosTarifaBasica property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeneficiosTarifaBasica(String value) {
            this.beneficiosTarifaBasica = value;
        }

        /**
         * Gets the value of the beneficiosTarifaClasica property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeneficiosTarifaClasica() {
            return beneficiosTarifaClasica;
        }

        /**
         * Sets the value of the beneficiosTarifaClasica property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeneficiosTarifaClasica(String value) {
            this.beneficiosTarifaClasica = value;
        }

        /**
         * Gets the value of the beneficiosTarifaAmplus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeneficiosTarifaAmplus() {
            return beneficiosTarifaAmplus;
        }

        /**
         * Sets the value of the beneficiosTarifaAmplus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeneficiosTarifaAmplus(String value) {
            this.beneficiosTarifaAmplus = value;
        }

        /**
         * Gets the value of the beneficiosTarifaFlexible property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeneficiosTarifaFlexible() {
            return beneficiosTarifaFlexible;
        }

        /**
         * Sets the value of the beneficiosTarifaFlexible property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeneficiosTarifaFlexible(String value) {
            this.beneficiosTarifaFlexible = value;
        }

        /**
         * Gets the value of the beneficiosTarifaPremier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeneficiosTarifaPremier() {
            return beneficiosTarifaPremier;
        }

        /**
         * Sets the value of the beneficiosTarifaPremier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeneficiosTarifaPremier(String value) {
            this.beneficiosTarifaPremier = value;
        }

        /**
         * Gets the value of the numAsientosTarifaBasica property.
         * 
         */
        public int getNumAsientosTarifaBasica() {
            return numAsientosTarifaBasica;
        }

        /**
         * Sets the value of the numAsientosTarifaBasica property.
         * 
         */
        public void setNumAsientosTarifaBasica(int value) {
            this.numAsientosTarifaBasica = value;
        }

        /**
         * Gets the value of the numAsientosTarifaClasica property.
         * 
         */
        public int getNumAsientosTarifaClasica() {
            return numAsientosTarifaClasica;
        }

        /**
         * Sets the value of the numAsientosTarifaClasica property.
         * 
         */
        public void setNumAsientosTarifaClasica(int value) {
            this.numAsientosTarifaClasica = value;
        }

        /**
         * Gets the value of the numAsientosTarifaAmplus property.
         * 
         */
        public int getNumAsientosTarifaAmplus() {
            return numAsientosTarifaAmplus;
        }

        /**
         * Sets the value of the numAsientosTarifaAmplus property.
         * 
         */
        public void setNumAsientosTarifaAmplus(int value) {
            this.numAsientosTarifaAmplus = value;
        }

        /**
         * Gets the value of the numAsientosTarifaFlexible property.
         * 
         */
        public int getNumAsientosTarifaFlexible() {
            return numAsientosTarifaFlexible;
        }

        /**
         * Sets the value of the numAsientosTarifaFlexible property.
         * 
         */
        public void setNumAsientosTarifaFlexible(int value) {
            this.numAsientosTarifaFlexible = value;
        }

        /**
         * Gets the value of the numAsientosTarifaPremier property.
         * 
         */
        public int getNumAsientosTarifaPremier() {
            return numAsientosTarifaPremier;
        }

        /**
         * Sets the value of the numAsientosTarifaPremier property.
         * 
         */
        public void setNumAsientosTarifaPremier(int value) {
            this.numAsientosTarifaPremier = value;
        }

    }

}
